datos = "Output/Infografia_Base_Municipal_Sin_Operaciones_2026_Enero.xlsx" |>  readxl::read_excel()

sumas = c(
  "Superficie (km2)",                                                                                                                                          
  "Población total",                                                                                                                                           
  "Población Rural",                                                                                                                                           
  "Población Urbana",                                                                                                                                          
  "Población Mujeres",                                                                                                                                         
  "Población Hombres",                                                                                                                                         
  "Población infantil (0-14 años)",                                                                                                                            
  "Población juvenil (15-29 años)",                                                                                                                            
  "Población (18 años y más)",                                                                                                                                 
  "Población adulta (30-59 años)",                                                                                                                             
  "Población adulta mayor (60 y más años)",                                                                                                                    
  "Usuarios de los Servicios de Salud",                                                                                                                        
  "Unidades médicas en servicio de las dependencias del sector público de salud por municipio",                                                                
  "Personal médico de las dependencias del sector público de salud por municipio",                                                                             
  "Población con discapacidad, limitación o con algún problema o condición mental",                                                                            
  "Viviendas particulares habitadas",                                                                                                                                                                                                                                   
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Refrigerador",                                                       
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Lavadora",                                                           
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Horno de microondas",                                                
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Automóvil o camioneta",                                              
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Motocicleta o motoneta",                                             
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Bicicleta que se utilice como medio de transporte",                  
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Algún aparato o dispositivo para oír radio",                         
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Televisor",                                                          
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Computadora, laptop o tablet",                                       
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Línea telefónica fija",                                              
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Teléfono celular",                                                   
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Internet",                                                           
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Servicio de televisión de paga (Cable o satelital)",                 
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Servicio de películas, música o videos de paga por Internet",        
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación Disponen Consola de videojuegos",                                             
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Refrigerador",                                                    
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Lavadora",                                                        
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Horno de microondas",                                             
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Automóvil o camioneta",                                           
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Motocicleta o motoneta",                                          
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Bicicleta que se utilice como medio de transporte",               
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Algún aparato o dispositivo para oír radio",                      
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Televisor",                                                       
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Computadora, laptop o tablet",                                    
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Línea telefónica fija",                                           
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Teléfono celular",                                                
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Internet",                                                        
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Servicio de televisión de paga (Cable o satelital)",              
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Servicio de películas, música o videos de paga por Internet",     
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No disponen Consola de videojuegos",                                          
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Refrigerador",                                                
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Lavadora",                                                    
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Horno de microondas",                                         
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Automóvil o camioneta",                                       
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Motocicleta o motoneta",                                      
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Bicicleta que se utilice como medio de transporte",           
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Algún aparato o dispositivo para oír radio",                  
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Televisor",                                                   
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Computadora, laptop o tablet",                                
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Línea telefónica fija",                                       
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Teléfono celular",                                            
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Internet",                                                    
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Servicio de televisión de paga (Cable o satelital)",          
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Servicio de películas, música o videos de paga por Internet", 
  "Disponibilidad de bienes y tecnologías de la información y de la comunicación No especificado Consola de videojuegos",                                      
  "Rezago educativo Personas 2020",                                                                                                                            
  "Carencia por acceso a los servicios de salud Personas 2020",                                                                                                
  "Carencia por acceso a la seguridad social Personas 2020",                                                                                                   
  "Carencia por calidad y espacios de la vivienda Personas 2020",                                                                                              
  "Carencia por acceso a los servicios básicos en la vivienda Personas 2020",                                                                                  
  "Carencia por acceso a la alimentación Personas 2020",                                                                                                       
  "Pobreza Personas 2020",                                                                                                                                     
  "Pobreza extrema Personas 2020",                                                                                                                             
  "Pobreza moderada Personas 2020",                                                                                                                            
  "Vulnerables por carencia social Personas 2020",                                                                                                             
  "Vulnerables por ingreso Personas 2020",                                                                                                                     
  "Seguridad Total",                                                                                                                                           
  "Seguridad Total Hombres",                                                                                                                                   
  "Seguridad Total Mujeres",                                                                                                                                   
  "Procedimientos Administrativos",                                                                                                                            
  "Procedimientos Administrativos A disposición de la guardia nacional",                                                                                       
  "Procedimientos Administrativos A disposición de la policia estatal",                                                                                        
  "Procedimientos Administrativos A disposición de la policia municipal",                                                                                      
  "Centros Penitenciarios",                                                                                                                                    
  "Centros de Reinserción",                                                                                                                                    
  "Centro Femenil de Reiserción Social",                                                                                                                       
  "Población Penitenciaria Hombres",                                                                                                                           
  "Población Penitenciaria Mujeres",                                                                                                                           
  "Total de delitos",                                                                                                                                          
  "Homicidio",                                                                                                                                                 
  "Secuestro",                                                                                                                                                 
  "Lesiones",                                                                                                                                                  
  "Extorsión",                                                                                                                                                 
  "Feminicidio",                                                                                                                                               
  "Narcomenudeo",                                                                                                                                              
  "Robo a casa habitación",                                                                                                                                    
  "Robo de vehículo automotor",                                                                                                                                
  "Robo a negocio",                                                                                                                                            
  "Violación",                                                                                                                                                 
  "Violencia familiar",                                                                                                                                        
  "Otros delitos",                                                                                                                                             
  "Plantas de tratamiento en operación, capacidad instalada y volumen tratado de aguas residuales por municipio y tipo de servicio según nivel de tratamiento",
  "Volumen tratado (Millones de metros cúbicos)",                                                                                                              
  "Longitud de la Red Carretera",                                                                                                                              
  "Carretras Federales",                                                                                                                                       
  "Alimentadoras Estatales",                                                                                                                                   
  "Caminos Rurales",                                                                                                                                           
  "Brechas mejoradas",                                                                                                                                         
  "Número de áreas protegidas",                                                                                                                                
  "Cantidad promedio diaria de residuos sólidos urbanos recolectados",                                                                                         
  "Sistema de recolección Casa por casa",                                                                                                                      
  "Sistema de recolección En un punto de recolección establecido",                                                                                             
  "Sistema de recolección Sistema de contenedores",                                                                                                            
  "Total de Vehiculos de motor 2021",                                                                                                                          
  "Total de Vehiculos de motor 2022",                                                                                                                          
  "Total de Vehiculos de motor 2023",                                                                                                                          
  "Automóviles Oficial 2021",                                                                                                                                  
  "Automóviles Oficial 2022",                                                                                                                                  
  "Automóviles Oficial 2023",                                                                                                                                  
  "Automóviles Público 2021",                                                                                                                                  
  "Automóviles Público 2022",                                                                                                                                  
  "Automóviles Público 2023",                                                                                                                                  
  "Automóviles Particular 2021",                                                                                                                               
  "Automóviles Particular 2022",                                                                                                                               
  "Automóviles Particular 2023",                                                                                                                               
  "Camiones de pasajeros Oficial 2021",                                                                                                                        
  "Camiones de pasajeros Oficial 2022",                                                                                                                        
  "Camiones de pasajeros Oficial 2023",                                                                                                                        
  "Camiones de pasajeros Público 2021",                                                                                                                        
  "Camiones de pasajeros Público 2022",                                                                                                                        
  "Camiones de pasajeros Público 2023",                                                                                                                        
  "Camiones de pasajeros Particular 2021",                                                                                                                     
  "Camiones de pasajeros Particular 2022",                                                                                                                     
  "Camiones de pasajeros Particular 2023",                                                                                                                     
  "Camiones y camionetas para carga Oficial 2021",                                                                                                             
  "Camiones y camionetas para carga Oficial 2022",                                                                                                             
  "Camiones y camionetas para carga Oficial 2023",                                                                                                             
  "Camiones y camionetas para carga Público 2021",                                                                                                             
  "Camiones y camionetas para carga Público 2022",                                                                                                             
  "Camiones y camionetas para carga Público 2023",                                                                                                             
  "Camiones y camionetas para carga Particular 2021",                                                                                                          
  "Camiones y camionetas para carga Particular 2022",                                                                                                          
  "Camiones y camionetas para carga Particular 2023",                                                                                                          
  "Motocicletas Oficial 2021",                                                                                                                                 
  "Motocicletas Oficial 2022",                                                                                                                                 
  "Motocicletas Oficial 2023",                                                                                                                                 
  "Motocicletas De alquiler 2021",                                                                                                                             
  "Motocicletas De alquiler 2022",                                                                                                                             
  "Motocicletas De alquiler 2023",                                                                                                                             
  "Motocicletas Particular 2021",                                                                                                                              
  "Motocicletas Particular 2022",                                                                                                                              
  "Motocicletas Particular 2023",                                                                                                                              
  "Accidentes de Tránsito Registrados",                                                                                                                        
  "Escuelas Total",                                                                                                                                            
  "Escuelas Educación Preescolar",                                                                                                                             
  "Escuelas Educación Primaria",                                                                                                                               
  "Escuelas Educación Secundaria",                                                                                                                             
  "Escuelas Educación Media Superior",                                                                                                                         
  "Escuelas Educación Superior",                                                                                                                               
  "Alumnos Total",                                                                                                                                             
  "Alumnos Educación Preescolar",                                                                                                                              
  "Alumnos Educación Primaria",                                                                                                                                
  "Alumnos Educación Secundaria",                                                                                                                              
  "Alumnos Educación Media Superior",                                                                                                                          
  "Alumnos Educación Superior",                                                                                                                                
  "Docentes Total",                                                                                                                                            
  "Docentes Educación Preescolar",                                                                                                                             
  "Docentes Educación Primaria",                                                                                                                               
  "Docentes Educación Secundaria",                                                                                                                             
  "Docentes Educación Media Superior",                                                                                                                         
  "Docentes Educación Superior",                                                                                                                               
  "Grado promedio de escolaridad",                                                                                                                             
  "Grado promedio de escolaridad Equivalencia",                                                                                                                
  "Población de 15 años y más",                                                                                                                                
  "Poblacion Analfabeta",                                                                                                                                      
  "Desayunos Integrados",                                                                                                                                      
  "Uniformes",                                                                                                                                                 
  "Becas",                                                                                                                                                     
  "Puntos de atención LICONSA",                                                                                                                                
  "Familias beneficiarias LICONSA",                                                                                                                            
  "Beneficiarios LICONSA",                                                                                                                                     
  "Dotación anual de leche fortificada (Litros) LICONSA",                                                                                                      
  "Importe de la venta de leche fortificada (Miles de pesos) LICONSA",                                                                                         
  "Tiendas Diconsa",                                                                                                                                           
  "Tianguis",                                                                                                                                                  
  "Mercados públicos",                                                                                                                                         
  "Centrales de abasto",                                                                                                                                       
  "Estaciones de servicio Gasolinerias",                                                                                                                       
  "Dispensarios de combustible Gasolinerias",                                                                                                                  
  "Población económicamente activa Total Total",                                                                                                               
  "Población económicamente activa Total Hombres",                                                                                                             
  "Población económicamente activa Total Mujeres",                                                                                                             
  "Población económicamente activa Ocupada Total",                                                                                                             
  "Población económicamente activa Ocupada Hombres",                                                                                                           
  "Población económicamente activa Ocupada Mujeres",                                                                                                           
  "Población económicamente activa Desocupada Total",                                                                                                          
  "Población económicamente activa Desocupada Hombres",                                                                                                        
  "Población económicamente activa Desocupada Mujeres",                                                                                                        
  "Población no económicamente activa Total",                                                                                                                  
  "Población no económicamente activa Hombres",                                                                                                                
  "Población no económicamente activa Mujeres",                                                                                                                
  "Población económicamente No especificado Total",                                                                                                            
  "Población económicamente No especificado Hombres",                                                                                                          
  "Población económicamente No especificado Mujeres",                                                                                                          
  "Unidades Económicas",                                                                                                                                       
  "Unidades Económicas Personal Ocupado",                                                                                                                      
  "Unidades Económicas Remuneraciones",                                                                                                                        
  "Unidades Económicas Producción bruta total (millones de pesos)",                                                                                            
  "Numero de Trabajadores",                                                                                                                                                                                                                                                
  "Ingresos por remesas Enero-Septiembre(2025)",                                                                                                                                                                                                                                             
  "Total Hospedajes",                                                                                                                                          
  "Hoteles",                                                                                                                                                   
  "Moteles",                                                                                                                                                   
  "Cabañas, villas y similares",                                                                                                                               
  "Campamentos y albergues recreativos",                                                                                                                       
  "Pensiones y casas de huéspedes",                                                                                                                            
  "Departamentos y casas amuebladas con servicio de hotelería",                                                                                                
  "Total establecimientos bebidas",                                                                                                                            
  "Restaurantes",                                                                                                                                              
  "Servicios de preparación de otros alimentos para consumo inmediato",                                                                                        
  "Cafeterías, fuentes de sodas, neverías, refresquerías y similares",                                                                                         
  "Centros nocturnos, discotecas y similares",                                                                                                                 
  "Bares, cantinas y similares",                                                                                                                               
  "Bibliotecas públicas",                                                                                                                                      
  "Personal ocupado Bibliotecas",                                                                                                                              
  "Títulos Bibliotecas",                                                                                                                                       
  "Libros en existencia Bibliotecas",                                                                                                                          
  "Consultas realizadas Bibliotecas",                                                                                                                          
  "Usuarios Bibliotecas",                                                                                                                                      
  "Centros y unidades deportivas",                                                                                                                             
  "Superficie Sembrada (has.)",                                                                                                                                
  "Superficie Cosechada (has)",                                                                                                                                
  "Volumen de la Producción (tons)",                                                                                                                           
  "Valor de la Producción (miles de pesos)",                                                                                                                   
  "Producción en toneladas de ganado en pie de tipo bovino",                                                                                                   
  "Valor de la producción en miles de pesos de ganado en pie de tipo bovino",                                                                                  
  "Producción en toneladas de ganado en pie de tipo porcino",                                                                                                  
  "valor de la producción en miles de pesos de ganado en pie de tipo porcino",                                                                                 
  "Producción en toneladas de ganado en pie de tipo ovino",                                                                                                    
  "Valor de la producción en miles de pesos de ganado en pie de tipo ovino",                                                                                   
  "Producción en toneladas de ganado en pie de tipo caprino",                                                                                                  
  "Valor de la producción en miles de pesos de ganado en pie de tipo caprino",                                                                                 
  "Producción en toneladas de aves en pie",                                                                                                                    
  "Valor de la producción en miles de pesos de aves en pie",                                                                                                   
  "Producción en toneladas de guajolotes en pie",                                                                                                              
  "Valor de la producción en miles de pesos de guajolotes en pie",                                                                                             
  "Producción en toneladas de carne de canal de tipo bovino",                                                                                                  
  "Valor de la producción en miles de pesos de carne de canal de tipo bovino",                                                                                 
  "Producción en toneladas de carne de canal de tipo porcino",                                                                                                 
  "Valor de la producción en miles de pesos de carne de canal de tipo porcino",                                                                                
  "Producción en toneladas de carne de canal de tipo ovino",                                                                                                   
  "Valor de la producción en miles de pesos de carne de canal de tipo ovino",                                                                                  
  "Producción en toneladas de carne de canal de tipo caprino",                                                                                                 
  "Valor de la producción en miles de pesos de carne de canal de tipo caprino",                                                                                
  "Producción en toneladas de carne de canal aves",                                                                                                            
  "valor de la producción en miles de pesos de carne de canal aves",                                                                                           
  "Producción en toneladas de carne de canal guajolotes",                                                                                                      
  "Valor de la producción en miles de pesos de carne de canal guajolotes",                                                                                     
  "Producción de leche en miles de litros de ganado de tipo bovino",                                                                                           
  "Valor de la producción de leche en miles de pesos de ganado de tipo bovino",                                                                                
  "Producción de leche en miles de litros de ganado de tipo caprino",                                                                                          
  "Valor de la producción de leche en miles de pesos de ganado de tipo caprino",                                                                               
  "Producción de huevo para plato en miles de litros",                                                                                                         
  "Valor de la producción de huevo para plato en miles de pesos",                                                                                              
  "Producción de miel en miles de litros",                                                                                                                     
  "Valor de la producción de miel en miles de pesos",                                                                                                          
  "Producción de cera en miles de litros",                                                                                                                     
  "Valor de la producción de cera en miles de pesos",                                                                                                          
  "Producción de lana en miles de litros",                                                                                                                     
  "Valor de la producción de lana en miles de pesos",                                                                                                          
  "Aceituna (Tonelada) Superficie Cosechada",                                                                                                                  
  "Aceituna (Tonelada) Superficie sembrada",                                                                                                                   
  "Aceituna (Tonelada) Valor de la Producción",                                                                                                                
  "Aceituna (Tonelada) Volumen de la Producción",                                                                                                              
  "Acelga (Tonelada) Superficie Cosechada",                                                                                                                    
  "Acelga (Tonelada) Superficie sembrada",                                                                                                                     
  "Acelga (Tonelada) Valor de la Producción",                                                                                                                  
  "Acelga (Tonelada) Volumen de la Producción",                                                                                                                
  "Aguacate (Tonelada) Superficie Cosechada",                                                                                                                  
  "Aguacate (Tonelada) Superficie sembrada",                                                                                                                   
  "Aguacate (Tonelada) Valor de la Producción",                                                                                                                
  "Aguacate (Tonelada) Volumen de la Producción",                                                                                                              
  "Ajo (Tonelada) Superficie Cosechada",                                                                                                                       
  "Ajo (Tonelada) Superficie sembrada",                                                                                                                        
  "Ajo (Tonelada) Valor de la Producción",                                                                                                                     
  "Ajo (Tonelada) Volumen de la Producción",                                                                                                                   
  "Alfalfa (Tonelada) Superficie Cosechada",                                                                                                                   
  "Alfalfa (Tonelada) Superficie sembrada",                                                                                                                    
  "Alfalfa (Tonelada) Valor de la Producción",                                                                                                                 
  "Alfalfa (Tonelada) Volumen de la Producción",                                                                                                               
  "Arvejón (Tonelada) Superficie Cosechada",                                                                                                                   
  "Arvejón (Tonelada) Superficie sembrada",                                                                                                                    
  "Arvejón (Tonelada) Valor de la Producción",                                                                                                                 
  "Arvejón (Tonelada) Volumen de la Producción",                                                                                                               
  "Avena forrajera en verde (Tonelada) Superficie Cosechada",                                                                                                  
  "Avena forrajera en verde (Tonelada) Superficie sembrada",                                                                                                   
  "Avena forrajera en verde (Tonelada) Valor de la Producción",                                                                                                
  "Avena forrajera en verde (Tonelada) Volumen de la Producción",                                                                                              
  "Avena grano (Tonelada) Superficie Cosechada",                                                                                                               
  "Avena grano (Tonelada) Superficie sembrada",                                                                                                                
  "Avena grano (Tonelada) Valor de la Producción",                                                                                                             
  "Avena grano (Tonelada) Volumen de la Producción",                                                                                                           
  "Betabel (Tonelada) Superficie Cosechada",                                                                                                                   
  "Betabel (Tonelada) Superficie sembrada",                                                                                                                    
  "Betabel (Tonelada) Valor de la Producción",                                                                                                                 
  "Betabel (Tonelada) Volumen de la Producción",                                                                                                               
  "Brócoli (Tonelada) Superficie Cosechada",                                                                                                                   
  "Brócoli (Tonelada) Superficie sembrada",                                                                                                                    
  "Brócoli (Tonelada) Valor de la Producción",                                                                                                                 
  "Brócoli (Tonelada) Volumen de la Producción",                                                                                                               
  "Cacahuate (Tonelada) Superficie Cosechada",                                                                                                                 
  "Cacahuate (Tonelada) Superficie sembrada",                                                                                                                  
  "Cacahuate (Tonelada) Valor de la Producción",                                                                                                               
  "Cacahuate (Tonelada) Volumen de la Producción",                                                                                                             
  "Café cereza (Tonelada) Superficie Cosechada",                                                                                                               
  "Café cereza (Tonelada) Superficie sembrada",                                                                                                                
  "Café cereza (Tonelada) Valor de la Producción",                                                                                                             
  "Café cereza (Tonelada) Volumen de la Producción",                                                                                                           
  "Calabacita (Tonelada) Superficie Cosechada",                                                                                                                
  "Calabacita (Tonelada) Superficie sembrada",                                                                                                                 
  "Calabacita (Tonelada) Valor de la Producción",                                                                                                              
  "Calabacita (Tonelada) Volumen de la Producción",                                                                                                            
  "Canola (Tonelada) Superficie Cosechada",                                                                                                                    
  "Canola (Tonelada) Superficie sembrada",                                                                                                                     
  "Canola (Tonelada) Valor de la Producción",                                                                                                                  
  "Canola (Tonelada) Volumen de la Producción",                                                                                                                
  "Caña de azúcar otro uso (Tonelada) Superficie Cosechada",                                                                                                   
  "Caña de azúcar otro uso (Tonelada) Superficie sembrada",                                                                                                    
  "Caña de azúcar otro uso (Tonelada) Valor de la Producción",                                                                                                 
  "Caña de azúcar otro uso (Tonelada) Volumen de la Producción",                                                                                               
  "Cebada forrajera en verde (Tonelada) Superficie Cosechada",                                                                                                 
  "Cebada forrajera en verde (Tonelada) Superficie sembrada",                                                                                                  
  "Cebada forrajera en verde (Tonelada) Valor de la Producción",                                                                                               
  "Cebada forrajera en verde (Tonelada) Volumen de la Producción",                                                                                             
  "Cebada grano (Tonelada) Superficie Cosechada",                                                                                                              
  "Cebada grano (Tonelada) Superficie sembrada",                                                                                                               
  "Cebada grano (Tonelada) Valor de la Producción",                                                                                                            
  "Cebada grano (Tonelada) Volumen de la Producción",                                                                                                          
  "Cebolla (Tonelada) Superficie Cosechada",                                                                                                                   
  "Cebolla (Tonelada) Superficie sembrada",                                                                                                                    
  "Cebolla (Tonelada) Valor de la Producción",                                                                                                                 
  "Cebolla (Tonelada) Volumen de la Producción",                                                                                                               
  "Chícharo (Tonelada) Superficie Cosechada",                                                                                                                  
  "Chícharo (Tonelada) Superficie sembrada",                                                                                                                   
  "Chícharo (Tonelada) Valor de la Producción",                                                                                                                
  "Chícharo (Tonelada) Volumen de la Producción",                                                                                                              
  "Chile verde (Tonelada) Superficie Cosechada",                                                                                                               
  "Chile verde (Tonelada) Superficie sembrada",                                                                                                                
  "Chile verde (Tonelada) Valor de la Producción",                                                                                                             
  "Chile verde (Tonelada) Volumen de la Producción",                                                                                                           
  "Cilantro (Tonelada) Superficie Cosechada",                                                                                                                  
  "Cilantro (Tonelada) Superficie sembrada",                                                                                                                   
  "Cilantro (Tonelada) Valor de la Producción",                                                                                                                
  "Cilantro (Tonelada) Volumen de la Producción",                                                                                                              
  "Ciruela (Tonelada) Superficie Cosechada",                                                                                                                   
  "Ciruela (Tonelada) Superficie sembrada",                                                                                                                    
  "Ciruela (Tonelada) Valor de la Producción",                                                                                                                 
  "Ciruela (Tonelada) Volumen de la Producción",                                                                                                               
  "Col (repollo) (Tonelada) Superficie Cosechada",                                                                                                             
  "Col (repollo) (Tonelada) Superficie sembrada",                                                                                                              
  "Col (repollo) (Tonelada) Valor de la Producción",                                                                                                           
  "Col (repollo) (Tonelada) Volumen de la Producción",                                                                                                         
  "Coliflor (Tonelada) Superficie Cosechada",                                                                                                                  
  "Coliflor (Tonelada) Superficie sembrada",                                                                                                                   
  "Coliflor (Tonelada) Valor de la Producción",                                                                                                                
  "Coliflor (Tonelada) Volumen de la Producción",                                                                                                              
  "Durazno (Tonelada) Superficie Cosechada",                                                                                                                   
  "Durazno (Tonelada) Superficie sembrada",                                                                                                                    
  "Durazno (Tonelada) Valor de la Producción",                                                                                                                 
  "Durazno (Tonelada) Volumen de la Producción",                                                                                                               
  "Ejote (Tonelada) Superficie Cosechada",                                                                                                                     
  "Ejote (Tonelada) Superficie sembrada",                                                                                                                      
  "Ejote (Tonelada) Valor de la Producción",                                                                                                                   
  "Ejote (Tonelada) Volumen de la Producción",                                                                                                                 
  "Elote (Tonelada) Superficie Cosechada",                                                                                                                     
  "Elote (Tonelada) Superficie sembrada",                                                                                                                      
  "Elote (Tonelada) Valor de la Producción",                                                                                                                   
  "Elote (Tonelada) Volumen de la Producción",                                                                                                                 
  "Espárrago (Tonelada) Superficie Cosechada",                                                                                                                 
  "Espárrago (Tonelada) Superficie sembrada",                                                                                                                  
  "Espárrago (Tonelada) Valor de la Producción",                                                                                                               
  "Espárrago (Tonelada) Volumen de la Producción",                                                                                                             
  "Espinaca (Tonelada) Superficie Cosechada",                                                                                                                  
  "Espinaca (Tonelada) Superficie sembrada",                                                                                                                   
  "Espinaca (Tonelada) Valor de la Producción",                                                                                                                
  "Espinaca (Tonelada) Volumen de la Producción",                                                                                                              
  "Frijol (Tonelada) Superficie Cosechada",                                                                                                                    
  "Frijol (Tonelada) Superficie sembrada",                                                                                                                     
  "Frijol (Tonelada) Valor de la Producción",                                                                                                                  
  "Frijol (Tonelada) Volumen de la Producción",                                                                                                                
  "Girasol (Tonelada) Superficie Cosechada",                                                                                                                   
  "Girasol (Tonelada) Superficie sembrada",                                                                                                                    
  "Girasol (Tonelada) Valor de la Producción",                                                                                                                 
  "Girasol (Tonelada) Volumen de la Producción",                                                                                                               
  "Granada (Tonelada) Superficie Cosechada",                                                                                                                   
  "Granada (Tonelada) Superficie sembrada",                                                                                                                    
  "Granada (Tonelada) Valor de la Producción",                                                                                                                 
  "Granada (Tonelada) Volumen de la Producción",                                                                                                               
  "Guayaba (Tonelada) Superficie Cosechada",                                                                                                                   
  "Guayaba (Tonelada) Superficie sembrada",                                                                                                                    
  "Guayaba (Tonelada) Valor de la Producción",                                                                                                                 
  "Guayaba (Tonelada) Volumen de la Producción",                                                                                                               
  "Haba grano (Tonelada) Superficie Cosechada",                                                                                                                
  "Haba grano (Tonelada) Superficie sembrada",                                                                                                                 
  "Haba grano (Tonelada) Valor de la Producción",                                                                                                              
  "Haba grano (Tonelada) Volumen de la Producción",                                                                                                            
  "Haba verde (Tonelada) Superficie Cosechada",                                                                                                                
  "Haba verde (Tonelada) Superficie sembrada",                                                                                                                 
  "Haba verde (Tonelada) Valor de la Producción",                                                                                                              
  "Haba verde (Tonelada) Volumen de la Producción",                                                                                                            
  "Higo (Tonelada) Superficie Cosechada",                                                                                                                      
  "Higo (Tonelada) Superficie sembrada",                                                                                                                       
  "Higo (Tonelada) Valor de la Producción",                                                                                                                    
  "Higo (Tonelada) Volumen de la Producción",                                                                                                                  
  "Lechuga (Tonelada) Superficie Cosechada",                                                                                                                   
  "Lechuga (Tonelada) Superficie sembrada",                                                                                                                    
  "Lechuga (Tonelada) Valor de la Producción",                                                                                                                 
  "Lechuga (Tonelada) Volumen de la Producción",                                                                                                               
  "Lima (Tonelada) Superficie Cosechada",                                                                                                                      
  "Lima (Tonelada) Superficie sembrada",                                                                                                                       
  "Lima (Tonelada) Valor de la Producción",                                                                                                                    
  "Lima (Tonelada) Volumen de la Producción",                                                                                                                  
  "Limón (Tonelada) Superficie Cosechada",                                                                                                                     
  "Limón (Tonelada) Superficie sembrada",                                                                                                                      
  "Limón (Tonelada) Valor de la Producción",                                                                                                                   
  "Limón (Tonelada) Volumen de la Producción",                                                                                                                 
  "Litchi (Tonelada) Superficie Cosechada",                                                                                                                    
  "Litchi (Tonelada) Superficie sembrada",                                                                                                                     
  "Litchi (Tonelada) Valor de la Producción",                                                                                                                  
  "Litchi (Tonelada) Volumen de la Producción",                                                                                                                
  "Macadamia (Tonelada) Superficie Cosechada",                                                                                                                 
  "Macadamia (Tonelada) Superficie sembrada",                                                                                                                  
  "Macadamia (Tonelada) Valor de la Producción",                                                                                                               
  "Macadamia (Tonelada) Volumen de la Producción",                                                                                                             
  "Maguey (Tonelada) Superficie Cosechada",                                                                                                                    
  "Maguey (Tonelada) Superficie sembrada",                                                                                                                     
  "Maguey (Tonelada) Valor de la Producción",                                                                                                                  
  "Maguey (Tonelada) Volumen de la Producción",                                                                                                                
  "Maguey mixiotero (Tonelada) Superficie Cosechada",                                                                                                          
  "Maguey mixiotero (Tonelada) Superficie sembrada",                                                                                                           
  "Maguey mixiotero (Tonelada) Valor de la Producción",                                                                                                        
  "Maguey mixiotero (Tonelada) Volumen de la Producción",                                                                                                      
  "Maguey pulquero (Miles de lts.) Superficie Cosechada",                                                                                                      
  "Maguey pulquero (Miles de lts.) Superficie sembrada",                                                                                                       
  "Maguey pulquero (Miles de lts.) Valor de la Producción",                                                                                                    
  "Maguey pulquero (Miles de lts.) Volumen de la Producción",                                                                                                  
  "Maíz forrajero en verde (Tonelada) Superficie Cosechada",                                                                                                   
  "Maíz forrajero en verde (Tonelada) Superficie sembrada",                                                                                                    
  "Maíz forrajero en verde (Tonelada) Valor de la Producción",                                                                                                 
  "Maíz forrajero en verde (Tonelada) Volumen de la Producción",                                                                                               
  "Maíz grano (Tonelada) Superficie Cosechada",                                                                                                                
  "Maíz grano (Tonelada) Superficie sembrada",                                                                                                                 
  "Maíz grano (Tonelada) Valor de la Producción",                                                                                                              
  "Maíz grano (Tonelada) Volumen de la Producción",                                                                                                            
  "Mandarina (Tonelada) Superficie Cosechada",                                                                                                                 
  "Mandarina (Tonelada) Superficie sembrada",                                                                                                                  
  "Mandarina (Tonelada) Valor de la Producción",                                                                                                               
  "Mandarina (Tonelada) Volumen de la Producción",                                                                                                             
  "Mango (Tonelada) Superficie Cosechada",                                                                                                                     
  "Mango (Tonelada) Superficie sembrada",                                                                                                                      
  "Mango (Tonelada) Valor de la Producción",                                                                                                                   
  "Mango (Tonelada) Volumen de la Producción",                                                                                                                 
  "Mano de león (Manojo) Superficie Cosechada",                                                                                                                
  "Mano de león (Manojo) Superficie sembrada",                                                                                                                 
  "Mano de león (Manojo) Valor de la Producción",                                                                                                              
  "Mano de león (Manojo) Volumen de la Producción",                                                                                                            
  "Manzana (Tonelada) Superficie Cosechada",                                                                                                                   
  "Manzana (Tonelada) Superficie sembrada",                                                                                                                    
  "Manzana (Tonelada) Valor de la Producción",                                                                                                                 
  "Manzana (Tonelada) Volumen de la Producción",                                                                                                               
  "Nabo forrajero (Tonelada) Superficie Cosechada",                                                                                                            
  "Nabo forrajero (Tonelada) Superficie sembrada",                                                                                                             
  "Nabo forrajero (Tonelada) Valor de la Producción",                                                                                                          
  "Nabo forrajero (Tonelada) Volumen de la Producción",                                                                                                        
  "Naranja (Tonelada) Superficie Cosechada",                                                                                                                   
  "Naranja (Tonelada) Superficie sembrada",                                                                                                                    
  "Naranja (Tonelada) Valor de la Producción",                                                                                                                 
  "Naranja (Tonelada) Volumen de la Producción",                                                                                                               
  "Nopalitos (Tonelada) Superficie Cosechada",                                                                                                                 
  "Nopalitos (Tonelada) Superficie sembrada",                                                                                                                  
  "Nopalitos (Tonelada) Valor de la Producción",                                                                                                               
  "Nopalitos (Tonelada) Volumen de la Producción",                                                                                                             
  "Nube (Manojo) Superficie Cosechada",                                                                                                                        
  "Nube (Manojo) Superficie sembrada",                                                                                                                         
  "Nube (Manojo) Valor de la Producción",                                                                                                                      
  "Nube (Manojo) Volumen de la Producción",                                                                                                                    
  "Nuez (Tonelada) Superficie Cosechada",                                                                                                                      
  "Nuez (Tonelada) Superficie sembrada",                                                                                                                       
  "Nuez (Tonelada) Valor de la Producción",                                                                                                                    
  "Nuez (Tonelada) Volumen de la Producción",                                                                                                                  
  "Papa (Tonelada) Superficie Cosechada",                                                                                                                      
  "Papa (Tonelada) Superficie sembrada",                                                                                                                       
  "Papa (Tonelada) Valor de la Producción",                                                                                                                    
  "Papa (Tonelada) Volumen de la Producción",                                                                                                                  
  "Pastos y praderas (Tonelada) Superficie Cosechada",                                                                                                         
  "Pastos y praderas (Tonelada) Superficie sembrada",                                                                                                          
  "Pastos y praderas (Tonelada) Valor de la Producción",                                                                                                       
  "Pastos y praderas (Tonelada) Volumen de la Producción",                                                                                                     
  "Pepino (Tonelada) Superficie Cosechada",                                                                                                                    
  "Pepino (Tonelada) Superficie sembrada",                                                                                                                     
  "Pepino (Tonelada) Valor de la Producción",                                                                                                                  
  "Pepino (Tonelada) Volumen de la Producción",                                                                                                                
  "Pera (Tonelada) Superficie Cosechada",                                                                                                                      
  "Pera (Tonelada) Superficie sembrada",                                                                                                                       
  "Pera (Tonelada) Valor de la Producción",                                                                                                                    
  "Pera (Tonelada) Volumen de la Producción",                                                                                                                  
  "Piña (Tonelada) Superficie Cosechada",                                                                                                                      
  "Piña (Tonelada) Superficie sembrada",                                                                                                                       
  "Piña (Tonelada) Valor de la Producción",                                                                                                                    
  "Piña (Tonelada) Volumen de la Producción",                                                                                                                  
  "Plátano (Tonelada) Superficie Cosechada",                                                                                                                   
  "Plátano (Tonelada) Superficie sembrada",                                                                                                                    
  "Plátano (Tonelada) Valor de la Producción",                                                                                                                 
  "Plátano (Tonelada) Volumen de la Producción",                                                                                                               
  "Rábano (Tonelada) Superficie Cosechada",                                                                                                                    
  "Rábano (Tonelada) Superficie sembrada",                                                                                                                     
  "Rábano (Tonelada) Valor de la Producción",                                                                                                                  
  "Rábano (Tonelada) Volumen de la Producción",                                                                                                                
  "Rosa (Gruesa) Superficie Cosechada",                                                                                                                        
  "Rosa (Gruesa) Superficie sembrada",                                                                                                                         
  "Rosa (Gruesa) Valor de la Producción",                                                                                                                      
  "Rosa (Gruesa) Volumen de la Producción",                                                                                                                    
  "Sorgo grano (Tonelada) Superficie Cosechada",                                                                                                               
  "Sorgo grano (Tonelada) Superficie sembrada",                                                                                                                
  "Sorgo grano (Tonelada) Valor de la Producción",                                                                                                             
  "Sorgo grano (Tonelada) Volumen de la Producción",                                                                                                           
  "Tomate rojo (jitomate) (Tonelada) Superficie Cosechada",                                                                                                    
  "Tomate rojo (jitomate) (Tonelada) Superficie sembrada",                                                                                                     
  "Tomate rojo (jitomate) (Tonelada) Valor de la Producción",                                                                                                  
  "Tomate rojo (jitomate) (Tonelada) Volumen de la Producción",                                                                                                
  "Tomate verde (Tonelada) Superficie Cosechada",                                                                                                              
  "Tomate verde (Tonelada) Superficie sembrada",                                                                                                               
  "Tomate verde (Tonelada) Valor de la Producción",                                                                                                            
  "Tomate verde (Tonelada) Volumen de la Producción",                                                                                                          
  "Trigo forrajero verde (Tonelada) Superficie Cosechada",                                                                                                     
  "Trigo forrajero verde (Tonelada) Superficie sembrada",                                                                                                      
  "Trigo forrajero verde (Tonelada) Valor de la Producción",                                                                                                   
  "Trigo forrajero verde (Tonelada) Volumen de la Producción",                                                                                                 
  "Trigo grano (Tonelada) Superficie Cosechada",                                                                                                               
  "Trigo grano (Tonelada) Superficie sembrada",                                                                                                                
  "Trigo grano (Tonelada) Valor de la Producción",                                                                                                             
  "Trigo grano (Tonelada) Volumen de la Producción",                                                                                                           
  "Triticale forrajero en verde (Tonelada) Superficie Cosechada",                                                                                              
  "Triticale forrajero en verde (Tonelada) Superficie sembrada",                                                                                               
  "Triticale forrajero en verde (Tonelada) Valor de la Producción",                                                                                            
  "Triticale forrajero en verde (Tonelada) Volumen de la Producción",                                                                                          
  "Tuna (Tonelada) Superficie Cosechada",                                                                                                                      
  "Tuna (Tonelada) Superficie sembrada",                                                                                                                       
  "Tuna (Tonelada) Valor de la Producción",                                                                                                                    
  "Tuna (Tonelada) Volumen de la Producción",                                                                                                                  
  "Zarzamora (Tonelada) Superficie Cosechada",                                                                                                                 
  "Zarzamora (Tonelada) Superficie sembrada",                                                                                                                  
  "Zarzamora (Tonelada) Valor de la Producción",                                                                                                               
  "Zarzamora (Tonelada) Volumen de la Producción",                                                                                                             
  "Zempoalxochitl (Tonelada) Superficie Cosechada",                                                                                                            
  "Zempoalxochitl (Tonelada) Superficie sembrada",                                                                                                             
  "Zempoalxochitl (Tonelada) Valor de la Producción",                                                                                                          
  "Zempoalxochitl (Tonelada) Volumen de la Producción",                                                                                                        
  "Población de 3 años y más que habla alguna lengua indígena",                                                                                                
  "Se considera indígena",                                                                                                                                     
  "No se considera indígena",                                                                                                                                  
  "Kickapoo",                                                                                                                                                  
  "Pápago",                                                                                                                                                    
  "Tepehuano del sur",                                                                                                                                         
  "Tarahumara",                                                                                                                                                
  "Guarijío",                                                                                                                                                  
  "Yaqui",                                                                                                                                                     
  "Mayo",                                                                                                                                                      
  "Huichol",                                                                                                                                                   
  "Náhuatl",                                                                                                                                                   
  "Seri",                                                                                                                                                      
  "Otomí",                                                                                                                                                     
  "Mazahua",                                                                                                                                                   
  "Matlatzinca",                                                                                                                                               
  "Tlahuica",                                                                                                                                                  
  "Pame",                                                                                                                                                      
  "Chichimeco Jonaz",                                                                                                                                          
  "Chinanteco",                                                                                                                                                
  "Tlapaneco",                                                                                                                                                 
  "Mazateco",                                                                                                                                                  
  "Popoloca",                                                                                                                                                  
  "Zapoteco",                                                                                                                                                  
  "Chatino",                                                                                                                                                   
  "Amuzgo",                                                                                                                                                    
  "Mixteco",                                                                                                                                                   
  "Cuicateco",                                                                                                                                                 
  "Triqui",                                                                                                                                                    
  "Huasteco",                                                                                                                                                  
  "Maya",                                                                                                                                                      
  "Ch'ol",                                                                                                                                                     
  "Chontal de Tabasco",                                                                                                                                        
  "Tseltal",                                                                                                                                                   
  "Tsotsil",                                                                                                                                                   
  "Q'anjob'al",                                                                                                                                                
  "Tojolabal",                                                                                                                                                 
  "Q'eqchi'",                                                                                                                                                  
  "K'iche'",                                                                                                                                                   
  "Teko",                                                                                                                                                      
  "Mam",                                                                                                                                                       
  "Totonaco",                                                                                                                                                  
  "Tepehua",                                                                                                                                                   
  "Tarasco",                                                                                                                                                   
  "Mixe",                                                                                                                                                      
  "Zoque",                                                                                                                                                     
  "Huave",                                                                                                                                                     
  "Otras lenguas indígenas de América",                                                                                                                        
  "No especificado lengua indigena",                                                                                                                           
  "Chontal insuficientemente especificado",                                                                                                                    
  "Tepehuano insuficientemente especificado",                                                                                                                  
  "Popoluca insuficientemente especificado"   
)



prueba = datos |> 
  dplyr::group_by(Región) |> 
  dplyr::mutate(
    dplyr::across(
      .cols = dplyr::any_of(sumas),
      .fns = ~ sum(.x, na.rm = TRUE)
    )
  )
